scraper:
  base_url: "https://www.digikala.com/search/category-women-perfume/"
  max_pages: 3
  user_agent: "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36"
  output_dir: "clean_html_outputs"
  product_csv: "auto_detected_products.csv"
  product_data_csv: "product_data.csv"
  html_input_dir: "C:/Users/moham/Documents/GitHub/DigikalaScraping/clean_html_outputs"
  min_ngram_len: 4
  max_ngram_len: 12
  min_token_freq: 3
patterns:
  rating: '\d+\.?\d*\s*(?:out of|\/|\|)\s*\d+'
  reviews: '\d+\s*(?:review|comment|نظر)'
  price: '[\$€£]?[\d,.]+\s*(?:تومان|USD|EUR)?'
  discount: '\d+%'
  seller: 'آرشان|sold by|فروشنده'